# Generated by Django 5.1.4 on 2025-01-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('age', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
